/// @file main.cpp
/// @brief tools dispatcher entry — `tools <name> [args...]`, `tools list`, etc.

#include "SagaTools/Encoding.h"
#include "SagaTools/ProcessRunner.h"
#include "SagaTools/Registry.h"
#include "SagaTools/Resolver.h"

#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <iostream>
#include <string>
#include <vector>

#if defined(_WIN32)
    #include <windows.h>
#elif defined(__APPLE__)
    #include <mach-o/dyld.h>
    #include <climits>
#elif defined(__linux__)
    #include <climits>
    #include <unistd.h>
#endif

namespace
{

constexpr const char* kVersion = "0.2.0";

constexpr int kExitSuccess         = 0;
constexpr int kExitUsage           = 1;
constexpr int kExitToolUnavailable = 2;
constexpr int kExitRegistryError   = 3;
constexpr int kExitInstallerFail   = 4;

std::string ExtractRegistryFlag(std::vector<std::string>& args)
{
    for (std::size_t i = 0; i < args.size(); ++i)
    {
        if (args[i] == "--registry" && i + 1 < args.size())
        {
            const std::string value = args[i + 1];
            args.erase(args.begin() + i, args.begin() + i + 2);
            return value;
        }
    }
    return {};
}

/// Resolve the directory containing the running executable.
std::string ExecutableDirectory(const char* argv0)
{
    namespace fs = std::filesystem;

#if defined(_WIN32)
    wchar_t buf[MAX_PATH];
    const DWORD n = GetModuleFileNameW(nullptr, buf, MAX_PATH);
    if (n > 0 && n < MAX_PATH)
        return SagaTools::PathToUtf8(fs::path(buf).parent_path());
#elif defined(__APPLE__)
    char buf[PATH_MAX];
    uint32_t size = sizeof(buf);
    if (_NSGetExecutablePath(buf, &size) == 0)
    {
        std::error_code ec;
        fs::path resolved = fs::weakly_canonical(fs::path(buf), ec);
        if (!ec) return resolved.parent_path().string();
        return fs::path(buf).parent_path().string();
    }
#elif defined(__linux__)
    char buf[PATH_MAX];
    const ssize_t n = readlink("/proc/self/exe", buf, sizeof(buf) - 1);
    if (n > 0)
    {
        buf[n] = '\0';
        return fs::path(buf).parent_path().string();
    }
#endif

    if (!argv0 || !*argv0) return {};
    std::error_code ec;
    fs::path absolute = fs::absolute(SagaTools::PathFromUtf8(argv0), ec);
    if (ec) return {};
    return SagaTools::PathToUtf8(absolute.parent_path());
}

std::string AbsoluteInstallerPath(const std::string& baseDir, const std::string& raw)
{
    namespace fs = std::filesystem;
    const fs::path p = SagaTools::PathFromUtf8(raw);
    if (p.is_absolute()) return SagaTools::PathToUtf8(p);
    return SagaTools::PathToUtf8(
        fs::weakly_canonical(SagaTools::PathFromUtf8(baseDir) / p));
}

std::string FindPython()
{
    const std::string env = SagaTools::GetEnvUtf8("PYTHON");
    if (!env.empty()) return env;
#if defined(_WIN32)
    return "py";
#else
    return "python3";
#endif
}

/// Detect strings that look like un-decoded JSON \uXXXX escapes leaked into
/// a path, e.g. "Masau00fcstu00fc" -- the smoking gun of a parser that
/// dropped the backslash and treated the escape as literal text.
bool LooksLikeMojibake(const std::string& s) noexcept
{
    for (std::size_t i = 0; i + 5 < s.size(); ++i)
    {
        if (!std::isalpha(static_cast<unsigned char>(s[i]))) continue;
        if (s[i + 1] != 'u') continue;
        bool allHex = true;
        for (int k = 0; k < 4; ++k)
        {
            const char h = s[i + 2 + k];
            const bool ok = (h >= '0' && h <= '9')
                         || (h >= 'a' && h <= 'f')
                         || (h >= 'A' && h <= 'F');
            if (!ok) { allHex = false; break; }
        }
        if (allHex) return true;
    }
    return false;
}

void PrintPathDiagnostics(std::ostream& os, const std::string& expandedPath)
{
    if (LooksLikeMojibake(expandedPath))
    {
        os << "[tools]   ! detected `uXXXX`-style fragments in the path above.\n"
           << "[tools]     This usually means the registry was generated by an\n"
           << "[tools]     older dispatcher that did not decode JSON \\uXXXX escapes.\n"
           << "[tools]     Fix : re-run  `python3 Tools/SagaTools/setup.py --all`\n";
    }
}

void PrintUsage(std::ostream& os)
{
    os <<
        "tools — thin dispatcher for the SagaEngine tool ecosystem\n"
        "\n"
        "USAGE:\n"
        "    tools [--registry <path>] <command-or-tool> [args ...]\n"
        "\n"
        "BUILT-IN COMMANDS:\n"
        "    list                     list all registered tools and resolved paths\n"
        "    which <tool>             print the resolved path of <tool>, or '<unavailable>'\n"
        "    where <tool>             alias for `which`\n"
        "    run   <tool> [args ...]  explicit form of `tools <tool> [args ...]`\n"
        "    install <tool>           run the registered bootstrap installer for <tool>\n"
        "    --help, -h               print this help and exit 0\n"
        "    --version                print the dispatcher's version and exit 0\n"
        "\n"
        "ANY OTHER FIRST WORD is treated as a tool name and forwarded:\n"
        "\n"
        "    tools forge build --build=path/to/project/build\n"
        "    tools prism --repo-root . -o prism.raw.json\n"
        "\n"
        "REGISTRY DISCOVERY ORDER:\n"
        "    1. --registry <path>\n"
        "    2. $SAGATOOLS_REGISTRY\n"
        "    3. <exe-dir>/config/tools.registry.json   (where setup.py puts it)\n"
        "    4. ./tools.registry.json\n";
}

int CmdList(const SagaTools::Registry& registry)
{
    if (registry.Tools().empty() && registry.Installers().empty())
    {
        std::cout << "[tools] registry is empty.\n";
        return kExitSuccess;
    }
    std::cout << "[tools] registered tools:\n";
    for (const auto& [name, raw] : registry.Tools())
    {
        const SagaTools::Resolution r = SagaTools::Resolver::Resolve(registry, name);
        const std::string* installer = registry.FindInstallerRaw(name);
        std::cout << "  - " << name
                  << "   [" << (r.available ? r.source : std::string("unavailable")) << "]"
                  << "\n      raw       : " << raw
                  << "\n      expanded  : " << (r.expandedValue.empty() ? "(empty)" : r.expandedValue)
                  << "\n      resolved  : " << (r.available ? r.resolvedPath : std::string("(none)"))
                  << "\n      installer : " << (installer ? *installer : std::string("(none)"))
                  << "\n";
    }
    return kExitSuccess;
}

int CmdWhich(const SagaTools::Registry& registry, const std::string& name)
{
    if (!registry.FindToolRaw(name))
    {
        std::cerr << "[tools] unknown tool: '" << name << "'\n";
        return kExitToolUnavailable;
    }
    const SagaTools::Resolution r = SagaTools::Resolver::Resolve(registry, name);
    if (r.available) { std::cout << r.resolvedPath << "\n"; return kExitSuccess; }
    std::cout << "<unavailable>\n";
    return kExitToolUnavailable;
}

int CmdInstall(const SagaTools::Registry& registry, const std::string& name)
{
    const std::string* raw = registry.FindInstallerRaw(name);
    if (!raw)
    {
        std::cerr << "[tools] no installer registered for '" << name << "'.\n"
                  << "[tools] hint: add an entry under \"installers\" in the registry.\n";
        return kExitInstallerFail;
    }

    const std::string scriptPath = AbsoluteInstallerPath(registry.BaseDir(), *raw);
    if (!std::filesystem::exists(SagaTools::PathFromUtf8(scriptPath)))
    {
        std::cerr << "[tools] installer script not found:\n"
                  << "[tools]     " << scriptPath << "\n";
        PrintPathDiagnostics(std::cerr, scriptPath);
        return kExitInstallerFail;
    }

    const std::string python = FindPython();
    std::cerr << "[tools] installing '" << name << "': "
              << python << " " << scriptPath << "\n";

    std::string err;
    const int rc = SagaTools::ProcessRunner::Run(python, {scriptPath}, &err);
    if (rc < 0)
    {
        std::cerr << "[tools] could not invoke installer: " << err << "\n"
                  << "[tools] is `" << python << "` on PATH? (set $PYTHON to override)\n";
        return kExitInstallerFail;
    }
    if (rc != 0)
    {
        std::cerr << "[tools] installer exited with code " << rc << "\n";
        return rc;
    }
    std::cerr << "[tools] '" << name << "' installed.\n";
    return kExitSuccess;
}

int CmdDispatch(const SagaTools::Registry&      registry,
                const std::string&              name,
                const std::vector<std::string>& args)
{
    if (!registry.FindToolRaw(name))
    {
        std::cerr << "[tools] unknown tool: '" << name << "'\n"
                  << "[tools] hint: `tools list` shows what is registered.\n";
        return kExitToolUnavailable;
    }
    const SagaTools::Resolution r = SagaTools::Resolver::Resolve(registry, name);
    if (!r.available)
    {
        std::cerr << "[tools] tool '" << name << "' is not available on this host.\n"
                  << "[tools]   raw value      : " << *registry.FindToolRaw(name) << "\n"
                  << "[tools]   after expand   : " << (r.expandedValue.empty() ? "(empty)" : r.expandedValue) << "\n";
        PrintPathDiagnostics(std::cerr, r.expandedValue);
        if (registry.FindInstallerRaw(name))
            std::cerr << "[tools]   tip            : try  `tools install " << name << "`\n";
        else
            std::cerr << "[tools]   tip            : either set the missing env var or "
                      <<                "`--registry <path>` a different file.\n";
        return kExitToolUnavailable;
    }

    std::cerr << "[tools] " << name << " \xe2\x86\x92 " << r.resolvedPath << "\n";

    std::string err;
    const int rc = SagaTools::ProcessRunner::Run(r.resolvedPath, args, &err);
    if (rc < 0)
    {
        std::cerr << "[tools] launch failed: " << err << "\n";
        return kExitToolUnavailable;
    }
    return rc;
}

} // namespace

int main(int argc, char** argv)
{
#if defined(_WIN32)
    // Windows console defaults to OEM code page (CP850/CP857), which renders
    // our UTF-8 output as box-drawing mojibake. Switch input + output to
    // UTF-8 unconditionally — the dispatcher always emits UTF-8 internally.
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);
#endif

    std::vector<std::string> args;
    args.reserve(static_cast<std::size_t>(argc) > 0 ? argc - 1 : 0);
    for (int i = 1; i < argc; ++i) args.emplace_back(argv[i]);

    if (args.empty() || args[0] == "--help" || args[0] == "-h")
    {
        PrintUsage(std::cout);
        return kExitSuccess;
    }
    if (args[0] == "--version")
    {
        std::cout << "tools " << kVersion << "\n";
        return kExitSuccess;
    }

    const std::string registryFlag = ExtractRegistryFlag(args);
    if (args.empty()) { PrintUsage(std::cerr); return kExitUsage; }

    const std::string executableDir = ExecutableDirectory(argc > 0 ? argv[0] : nullptr);
    const std::string registryPath  = SagaTools::Registry::LocateFile(registryFlag, executableDir);
    if (registryPath.empty())
    {
        std::cerr << "[tools] no registry file found.\n"
                  << "[tools] expected one of: --registry, $SAGATOOLS_REGISTRY, "
                  << "<exe-dir>/config/tools.registry.json, ./tools.registry.json\n";
        return kExitRegistryError;
    }

    std::string loadError;
    auto registryOpt = SagaTools::Registry::LoadFromFile(registryPath, &loadError);
    if (!registryOpt)
    {
        std::cerr << "[tools] failed to load registry: " << loadError << "\n";
        return kExitRegistryError;
    }
    const SagaTools::Registry& registry = *registryOpt;

    const std::string head = args[0];
    args.erase(args.begin());

    if (head == "list")    return CmdList(registry);
    if (head == "which" || head == "where")
    {
        if (args.empty()) { std::cerr << "[tools] '" << head << "' requires a tool name.\n"; return kExitUsage; }
        return CmdWhich(registry, args[0]);
    }
    if (head == "install")
    {
        if (args.empty()) { std::cerr << "[tools] 'install' requires a tool name.\n"; return kExitUsage; }
        return CmdInstall(registry, args[0]);
    }
    if (head == "run")
    {
        if (args.empty()) { std::cerr << "[tools] 'run' requires a tool name.\n"; return kExitUsage; }
        const std::string toolName = args[0];
        args.erase(args.begin());
        return CmdDispatch(registry, toolName, args);
    }

    return CmdDispatch(registry, head, args);
}
