/// @file main.rs
/// @brief tools dispatcher entry - mirrors C++ main.cpp exactly.

mod registry;
mod resolver;
mod runner;

use std::env;
use std::io::Write;
use std::path::Path;
use std::process;

const VERSION: &str = "0.2.0";
const EXIT_SUCCESS: i32 = 0;
const EXIT_USAGE: i32 = 1;
const EXIT_TOOL_UNAVAILABLE: i32 = 2;
const EXIT_REGISTRY_ERROR: i32 = 3;
const EXIT_INSTALLER_FAIL: i32 = 4;

fn extract_registry_flag(args: &mut Vec<String>) -> String {
    let mut i = 0;
    while i < args.len() {
        if args[i] == "--registry" && i + 1 < args.len() {
            let value = args[i + 1].clone();
            args.drain(i..i + 2);
            return value;
        }
        i += 1;
    }
    String::new()
}

fn looks_like_mojibake(s: &str) -> bool {
    let bytes = s.as_bytes();
    let len = bytes.len();
    if len < 6 {
        return false;
    }
    for i in 0..len - 5 {
        if !bytes[i].is_ascii_alphabetic() {
            continue;
        }
        if bytes[i + 1] != b'u' {
            continue;
        }
        let mut all_hex = true;
        for k in 0..4 {
            let h = bytes[i + 2 + k];
            if !h.is_ascii_hexdigit() {
                all_hex = false;
                break;
            }
        }
        if all_hex {
            return true;
        }
    }
    false
}

fn print_path_diagnostics(os: &mut dyn Write, expanded_path: &str) {
    if looks_like_mojibake(expanded_path) {
        let _ = writeln!(os, "[tools]   ! detected `uXXXX`-style fragments in the path above.");
        let _ = writeln!(os, "[tools]     This usually means the registry was generated by an");
        let _ = writeln!(os, "[tools]     older dispatcher that did not decode JSON \\uXXXX escapes.");
        let _ = writeln!(os, "[tools]     Fix : re-run  `python3 Tools/SagaTools/setup.py --all`");
    }
}

fn print_usage(os: &mut dyn Write) {
    let _ = writeln!(os, "tools — thin dispatcher for the SagaEngine tool ecosystem\n");
    let _ = writeln!(os, "USAGE:");
    let _ = writeln!(os, "    tools [--registry <path>] <command-or-tool> [args ...]\n");
    let _ = writeln!(os, "BUILT-IN COMMANDS:");
    let _ = writeln!(os, "    list                     list all registered tools and resolved paths");
    let _ = writeln!(os, "    which <tool>             print the resolved path of <tool>, or '<unavailable>'");
    let _ = writeln!(os, "    where <tool>             alias for `which`");
    let _ = writeln!(os, "    run   <tool> [args ...]  explicit form of `tools <tool> [args ...]`");
    let _ = writeln!(os, "    install <tool>           run the registered bootstrap installer for <tool>");
    let _ = writeln!(os, "    --help, -h               print this help and exit 0");
    let _ = writeln!(os, "    --version                print the dispatcher's version and exit 0\n");
    let _ = writeln!(os, "ANY OTHER FIRST WORD is treated as a tool name and forwarded:\n");
    let _ = writeln!(os, "    tools forge build --build=path/to/project/build");
    let _ = writeln!(os, "    tools prism --repo-root . -o prism.raw.json\n");
    let _ = writeln!(os, "REGISTRY DISCOVERY ORDER:");
    let _ = writeln!(os, "    1. --registry <path>");
    let _ = writeln!(os, "    2. $SAGATOOLS_REGISTRY");
    let _ = writeln!(os, "    3. <exe-dir>/config/tools.registry.json   (where setup.py puts it)");
    let _ = writeln!(os, "    4. ./tools.registry.json");
}

fn cmd_list(registry: &registry::Registry) -> i32 {
    if registry.tools.is_empty() && registry.installers.is_empty() {
        println!("[tools] registry is empty.");
        return EXIT_SUCCESS;
    }
    
    println!("[tools] registered tools:");
    for (name, raw) in &registry.tools {
        let resolution = resolver::Resolver::resolve(registry, name);
        let installer = registry.find_installer_raw(name);
        
        let status = if resolution.available { "resolved" } else { "unavailable" };
        println!("  - {}   [{}]", name, status);
        println!("      raw       : {}", raw);
        
        let expanded = if resolution.expanded_value.is_empty() { "(empty)" } else { &resolution.expanded_value };
        println!("      expanded  : {}", expanded);
        
        let resolved = if resolution.available { &resolution.resolved_path } else { "(none)" };
        println!("      resolved  : {}", resolved);
        
        let installer_str = match installer {
            Some(s) => s.as_str(),
            None => "(none)"
        };
        println!("      installer : {}", installer_str);
    }
    EXIT_SUCCESS
}

fn cmd_which(registry: &registry::Registry, name: &str) -> i32 {
    if registry.find_tool_raw(name).is_none() {
        eprintln!("[tools] unknown tool: '{}'", name);
        return EXIT_TOOL_UNAVAILABLE;
    }
    
    let resolution = resolver::Resolver::resolve(registry, name);
    if resolution.available {
        println!("{}", resolution.resolved_path);
        EXIT_SUCCESS
    } else {
        println!("<unavailable>");
        EXIT_TOOL_UNAVAILABLE
    }
}

fn cmd_install(registry: &registry::Registry, name: &str) -> i32 {
    let raw = match registry.find_installer_raw(name) {
        Some(r) => r,
        None => {
            eprintln!("[tools] no installer registered for '{}'.", name);
            eprintln!("[tools] hint: add an entry under \"installers\" in the registry.");
            return EXIT_INSTALLER_FAIL;
        }
    };
    
    let script_path = registry.base_dir().join(raw.as_str()).to_string_lossy().into_owned();
    if !runner::Runner::file_exists(&script_path) {
        eprintln!("[tools] installer script not found:");
        eprintln!("[tools]     {}", script_path);
        let mut stderr = std::io::stderr();
        print_path_diagnostics(&mut stderr, &script_path);
        return EXIT_INSTALLER_FAIL;
    }
    
    let python = runner::Runner::find_python();
    eprintln!("[tools] installing '{}': {} {}", name, python, script_path);
    
    let args = vec![script_path.clone()];
    let (rc, err) = runner::Runner::run(&python, &args);
    
    if rc < 0 {
        eprintln!("[tools] could not invoke installer: {}", err);
        eprintln!("[tools] is `{}` on PATH? (set $PYTHON to override)", python);
        return EXIT_INSTALLER_FAIL;
    }
    
    if rc != 0 {
        eprintln!("[tools] installer exited with code {}", rc);
        return rc;
    }
    
    eprintln!("[tools] '{}' installed.", name);
    EXIT_SUCCESS
}

fn cmd_dispatch(registry: &registry::Registry, name: &str, args: &[String]) -> i32 {
    if registry.find_tool_raw(name).is_none() {
        eprintln!("[tools] unknown tool: '{}'", name);
        eprintln!("[tools] hint: `tools list` shows what is registered.");
        return EXIT_TOOL_UNAVAILABLE;
    }
    
    let resolution = resolver::Resolver::resolve(registry, name);
    if !resolution.available {
        eprintln!("[tools] tool '{}' is not available on this host.", name);
        
        let raw_val = match registry.find_tool_raw(name) {
            Some(s) => s.as_str(),
            None => ""
        };
        eprintln!("[tools]   raw value      : {}", raw_val);
        
        let expanded = if resolution.expanded_value.is_empty() { "(empty)" } else { &resolution.expanded_value };
        eprintln!("[tools]   after expand   : {}", expanded);
        
        let mut stderr = std::io::stderr();
        print_path_diagnostics(&mut stderr, &resolution.expanded_value);
        
        if registry.find_installer_raw(name).is_some() {
            eprintln!("[tools]   tip            : try  `tools install {}`", name);
        } else {
            eprintln!("[tools]   tip            : either set the missing env var or ");
            eprintln!("[tools]                 `--registry <path>` a different file.");
        }
        
        return EXIT_TOOL_UNAVAILABLE;
    }
    
    eprintln!("[tools] {} → {}", name, resolution.resolved_path);
    
    let (rc, err) = runner::Runner::run(&resolution.resolved_path, args);
    
    if rc < 0 {
        eprintln!("[tools] launch failed: {}", err);
        return EXIT_TOOL_UNAVAILABLE;
    }
    
    rc
}

fn main() {
    let mut args: Vec<String> = env::args().skip(1).collect();
    
    if args.is_empty() || args[0] == "--help" || args[0] == "-h" {
        print_usage(&mut std::io::stdout());
        process::exit(EXIT_SUCCESS);
    }
    
    if args[0] == "--version" {
        println!("tools {}", VERSION);
        process::exit(EXIT_SUCCESS);
    }
    
    let registry_flag = extract_registry_flag(&mut args);
    
    if args.is_empty() {
        print_usage(&mut std::io::stderr());
        process::exit(EXIT_USAGE);
    }
    
    let argv0 = env::args().next().unwrap_or_default();
    let executable_dir = if let Ok(exe_path) = env::current_exe() {
        if let Some(dir) = exe_path.parent() {
            dir.to_string_lossy().to_string()
        } else {
            String::new()
        }
    } else if !argv0.is_empty() {
        if let Some(dir) = Path::new(&argv0).parent() {
            dir.to_string_lossy().to_string()
        } else {
            String::new()
        }
    } else {
        String::new()
    };
    
    let registry_path = registry::Registry::locate_file(&registry_flag, Path::new(&executable_dir));
    let registry_path = match registry_path {
        Some(p) => p,
        None => {
            eprintln!("[tools] no registry file found.");
            eprintln!("[tools] expected one of: --registry, $SAGATOOLS_REGISTRY, ");
            eprintln!("[tools]   <exe-dir>/config/tools.registry.json, ./tools.registry.json");
            process::exit(EXIT_REGISTRY_ERROR);
        }
    };
    
    let registry = match registry::Registry::load_from_file(&registry_path) {
        Ok(r) => r,
        Err(e) => {
            eprintln!("[tools] failed to load registry: {}", e);
            process::exit(EXIT_REGISTRY_ERROR);
        }
    };
    
    let head = args[0].clone();
    args.remove(0);
    
    let exit_code = match head.as_str() {
        "list" => cmd_list(&registry),
        "which" | "where" => {
            if args.is_empty() {
                eprintln!("[tools] '{}' requires a tool name.", head);
                EXIT_USAGE
            } else {
                cmd_which(&registry, &args[0])
            }
        }
        "install" => {
            if args.is_empty() {
                eprintln!("[tools] 'install' requires a tool name.");
                EXIT_USAGE
            } else {
                cmd_install(&registry, &args[0])
            }
        }
        "run" => {
            if args.is_empty() {
                eprintln!("[tools] 'run' requires a tool name.");
                EXIT_USAGE
            } else {
                let tool_name = args[0].clone();
                args.remove(0);
                cmd_dispatch(&registry, &tool_name, &args)
            }
        }
        _ => cmd_dispatch(&registry, &head, &args),
    };
    
    process::exit(exit_code);
}
