/// @file ConnectionMigration.h
/// @brief Zone-transfer handoff protocol for seamless player migration.
///
/// Layer  : SagaServer / Networking / Server
/// Purpose: An MMO's world is larger than any single zone process can
///          hold.  When a player walks across a zone boundary we must
///          (a) pick them up on the destination zone, (b) preserve
///          their transform / inventory / cooldowns across the jump,
///          (c) keep replication working with as few visible glitches
///          as possible, and (d) do all of this without asking the
///          client to reconnect.
///
///          This header defines the *data contracts* for that protocol.
///          It is intentionally header-only: nothing here is opinionated
///          about transport (TCP, reliable UDP, shard-mesh RPC) because
///          the handoff is issued from ShardManager and may go through
///          any of the three depending on topology.
///
/// The migration dance:
///
///   1. Source zone decides the player needs to move (they crossed a
///      boundary, or a GM teleported them).  It builds a
///      `ZoneHandoffRequest` containing the player's ECS state snapshot
///      and the *destination* zone id.
///   2. Source zone sends `ZoneHandoffRequest` to the destination zone
///      via the shard mesh.  The source does NOT drop the client yet.
///   3. Destination zone validates, allocates the entity, and replies
///      with `ZoneHandoffAck`.  The ack carries an `acceptanceToken`
///      the client will quote on its next packet.
///   4. Source zone forwards the ack to the client as a
///      `ZoneMigrateDirective`.  The client closes its old session,
///      opens a new one against the destination endpoint, and sends
///      the token in its first packet.
///   5. Destination zone matches the token, promotes the entity to
///      live status, and begins replicating normally.
///
/// The source zone keeps the entity frozen (simulation paused, no
/// further outbound replication) from step 1 through step 4.  If the
/// ack never arrives (destination is down), the source zone rolls back
/// and the player stays put — a visible "zone server unavailable"
/// banner is better than a lost player.

#pragma once

#include "SagaEngine/Math/Vec3.h"
#include "SagaEngine/Math/Quat.h"

#include <array>
#include <cstdint>
#include <string>
#include <vector>

namespace SagaEngine::Networking {

// ─── Shared identifiers ──────────────────────────────────────────────────────

/// A 128-bit opaque token that binds a player's pending migration to
/// its first packet on the destination zone.  Randomly generated by the
/// destination and single-use.  128 bits gives us 2^64 tokens before
/// the collision probability reaches one in four billion, which is
/// plenty for any MMO's lifetime handoff volume.
struct AcceptanceToken
{
    std::array<std::uint8_t, 16> bytes{};
};

/// Zone identifier on the shard mesh.  Zones are spawned and torn down
/// dynamically so ids are NOT stable across a server lifetime — use the
/// ShardManager registry to resolve them to endpoints.
using ZoneId = std::uint32_t;

/// Stable cross-zone account identifier.  Matches the value the auth
/// layer produced at login time; reused here so the destination can
/// look up persistent data without another database round-trip.
using AccountId = std::uint64_t;

// ─── Entity payload carried across zones ────────────────────────────────────

/// Minimal snapshot of the migrating player's ECS state.  The actual
/// component set is larger — this header only captures the fields every
/// zone is guaranteed to understand.  Extended / game-specific fields
/// ride along in `extraBlob` as an opaque byte vector whose format is
/// owned by the scripting layer, not the engine.
struct ZoneHandoffEntityState
{
    AccountId          accountId = 0;
    std::uint32_t      avatarAssetId = 0;   ///< Reference into the asset DB.
    SagaEngine::Math::Vec3 position{};
    SagaEngine::Math::Quat rotation = SagaEngine::Math::Quat::Identity();
    SagaEngine::Math::Vec3 velocity{};
    std::uint32_t      currentHealth = 0;
    std::uint32_t      maxHealth     = 0;
    std::uint64_t      inventoryVersion = 0; ///< Monotonic; destination fetches if stale.
    std::vector<std::uint8_t> extraBlob;     ///< Game-specific opaque payload.
};

// ─── Handoff request (source → destination) ────────────────────────────────

/// Shape of the first message in the migration dance.  Sent over the
/// shard mesh; not user-visible.
struct ZoneHandoffRequest
{
    ZoneId                 sourceZone       = 0;
    ZoneId                 destinationZone  = 0;
    std::uint64_t          requestId        = 0; ///< Source-local sequence to match acks.
    std::uint64_t          issuedAtMs       = 0; ///< Source monotonic clock.
    ZoneHandoffEntityState state;
};

/// Reasons the destination may refuse a handoff.  Each one implies a
/// different recovery path on the source side.
enum class ZoneHandoffRejection : std::uint8_t
{
    None = 0,
    DestinationFull,       ///< Zone at capacity — source keeps player or routes elsewhere.
    DestinationNotReady,   ///< Zone is spawning/shutting down.
    UnknownDestination,    ///< Wrong zone id — mesh topology drift.
    InvalidEntityState,    ///< Payload failed destination-side validation.
    DuplicateRequestId,    ///< Source retried a handoff that already succeeded.
    InternalError          ///< Catch-all; log details on the destination side.
};

// ─── Handoff ack (destination → source) ─────────────────────────────────────

/// Reply message.  `rejection == None` means the handoff is accepted
/// and `acceptanceToken` is valid for the player's next packet.
struct ZoneHandoffAck
{
    std::uint64_t        requestId = 0;  ///< Echoes ZoneHandoffRequest::requestId.
    ZoneHandoffRejection rejection = ZoneHandoffRejection::None;
    AcceptanceToken      acceptanceToken;
    std::uint64_t        tokenExpiresAtMs = 0;  ///< Destination wall clock.
    std::string          endpoint;              ///< "host:port" for client reconnect.
};

// ─── Client-facing directive ────────────────────────────────────────────────

/// The shape forwarded to the *client* once the destination has
/// accepted.  This is what the client actually reacts to: it closes its
/// current session, reconnects to `endpoint`, and opens the new session
/// with `acceptanceToken` baked into the first handshake packet.
struct ZoneMigrateDirective
{
    AcceptanceToken acceptanceToken;
    std::uint64_t   tokenExpiresAtMs = 0;
    std::string     endpoint;
    ZoneId          destinationZone = 0;

    /// Optional displayable text ("Entering Crystalfall Caverns...").
    /// The engine passes this through untouched — scripting layer owns
    /// the localisation.
    std::string uiHint;
};

// ─── Bookkeeping helper ─────────────────────────────────────────────────────

/// Tiny state machine a ServerConnection embeds to know what phase of
/// the migration it is in.  Lives on the *source* side of the handoff;
/// the destination only sees a fresh, post-token connection.
enum class MigrationPhase : std::uint8_t
{
    None = 0,              ///< Default — normal gameplay.
    RequestSent,           ///< Shipped to destination, awaiting ack.
    DirectiveIssued,       ///< Client told to reconnect.
    Completed,             ///< Client acked directive — this slot can be reused.
    Aborted                ///< Rollback path — clear and resume on source.
};

} // namespace SagaEngine::Networking
